CREATE TYPE "TODO_SATE" AS ENUM (
    'TO_DO',
    'IN_PROGRESS',
    'DONE'
    );

CREATE TABLE "todo"
(
    "id"          INTEGER     NOT NULL UNIQUE GENERATED BY DEFAULT AS IDENTITY,
    "title"       VARCHAR(50) NOT NULL,
    "description" TEXT        NOT NULL,
    "created_at"  TIMESTAMP   NOT NULL default current_timestamp,
    "updated_at"  TIMESTAMP            default current_timestamp,
    PRIMARY KEY ("id")
);

CREATE INDEX "Todo_index_0"
    ON "todo" ("id");

CREATE TABLE app_user
(
    "id"         INTEGER     NOT NULL UNIQUE GENERATED BY DEFAULT AS IDENTITY,
    "fist_name"  VARCHAR(80) NOT NULL,
    "last_name"  VARCHAR(80) NOT NULL,
    "created_at" TIMESTAMP   NOT NULL DEFAULT current_timestamp,
    "update_at"  TIMESTAMP            DEFAULT current_timestamp,
    PRIMARY KEY ("id")
);

CREATE INDEX "table_1_index_0"
    ON app_user ("id");

CREATE TABLE "todo_user"
(
    "id"         INTEGER     NOT NULL UNIQUE GENERATED BY DEFAULT AS IDENTITY,
    "id_todo"    INTEGER     NOT NULL,
    "id_user"    INTEGER     NOT NULL,
    "state"      "TODO_SATE" NOT NULL,
    "updated_at" TIMESTAMP DEFAULT current_timestamp,
    CONSTRAINT fk_todo
        FOREIGN KEY (id_todo) REFERENCES todo (id),
    CONSTRAINT fk_app_user
        FOREIGN KEY (id_user) REFERENCES app_user (id),
    PRIMARY KEY ("id")
);

CREATE INDEX "todo_user_index_0"
    ON "todo_user" ("id");

CREATE UNIQUE INDEX "todo_user_index_1"
    ON "todo_user" ("id_todo", "id_user");

